version: 0.2

phases:
  pre_build:
    commands:
      - echo "🔧 AWS CLI version:"
      - aws --version
      - echo "🐳 Docker version:"
      - docker --version
      - echo "🔐 Getting ECR login token..."
      - echo "Logging into: 316497517854.dkr.ecr.ap-south-1.amazonaws.com"
      - TOKEN=$(aws ecr get-login-password --region ap-south-1)
      - echo $TOKEN | head -c 10 && echo " ...token retrieved"
      - echo "$TOKEN" | docker login --username AWS --password-stdin 316497517854.dkr.ecr.ap-south-1.amazonaws.com || (echo "❌ ECR login failed with code $?"; exit 1)

  build:
    commands:
      - echo "🚧 Building Docker image..."
      - docker build -t my-app .
      - docker tag my-app:latest 316497517854.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest

  post_build:
    commands:
      - echo "📤 Pushing Docker image to ECR..."
      - docker push 316497517854.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest
      - echo "📦 Creating imagedefinitions.json for ECS..."
      - printf '[{"name":"my-app-container","imageUri":"%s"}]' 316497517854.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
