version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws --version
      - docker --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 316497517854.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t my-app .
      - docker tag my-app:latest 316497517854.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 316497517854.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"my-app-container","imageUri":"%s"}]' 316497517854.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
